### ISSUE TITLE
Driver dies when command data is published

### ISSUE THREAD

**Issue by tonybaltovski** [smd-ros-devel/lynxmotion_ssc32u#3]
Using the new dev branch works well.  However, when I try to publish data to the command topic using rqt_ez_publisher or rostopic (shown below) from the command line, the driver dies.  After some debuging, I found line `386` in`ssc32_driver.cpp` on `dev` branch to be where it dies.  However, I cannot see an issue with the line.  Any thoughts on this?

Thanks in advance,

-Tony

```
rostopic pub /joint_controller/command trajectory_msgs/JointTjectory "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names:
- 'joint_1, joint_2, joint_3, joint_4, gripper'
points:
- positions: [0,0,0,0,0]
  velocities: [0]
  accelerations: [0]
  effort: [0]
  time_from_start: {secs: 0, nsecs: 0}" 
```
